name: selection
baseurl: /selection
description: Functor Transformations for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.1-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
